<?php

use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->delete();
        $sf_id = App\Studyfield::where('degree','BACHELOR OF INFORMATION TECHNOLOGY (BIT)')->pluck('sf_id');
        $sf_id2 = App\Studyfield::where('degree','BACHELOR IN COMPUTER ENGINEERING')->pluck('sf_id');
        $sf_id3 = App\Studyfield::where('degree','BACHELOR OF COMPUTER APPLICATIOIN (BCA)')->pluck('sf_id');

        $sub = [
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'BASIC ELECTRICAL SYSTEM & CIRCUIT (BESC)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'FUNDAMENTALS OF INFORMATION TECHNOLOGY(FIS)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'MATHEMATICS-I',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'TECHNICAL COMMUNICATION (ENGLISH)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'COMPUTER PROGRAMMING IN C',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'1st',
                'sub_name'=>'PRINCIPLES OF MANAGEMENT',
            ],


            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'MATHEMATICS-II',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'ELECTRONICS DEVICES & CIRCUITS (EDC)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'DIGITAL LOGIC',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'OBJECT ORIENTED PROGRAMMING IN C++',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'FINANCIAL MANAGEMENT & ACCOUNTING',
            ],

            ['sf_id'=>$sf_id[0],
                'semester'=>'2nd',
                'sub_name'=>'PRINCIPLES OF MANAGEMENT',
            ],


            ['sf_id'=>$sf_id[0],
                'semester'=>'3rd',
                'sub_name'=>'SYSTEM ANALYSIS & DESIGN (SAD)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'3rd',
                'sub_name'=>'MICROPROCESSOR & ASSEMBLY LANGUAGE',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'3rd',
                'sub_name'=>'DATA STRUCTURE & ALGORITHM (DSA)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'3rd',
                'sub_name'=>'USER INTERFACE DESIGN (UID)',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'3rd',
                'sub_name'=>'NUMERICAL METHODS',
            ],


            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'COMMUNICATION SYSTEM',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'COMPUTER ORGANIZATION',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'WEB TECHNOLOGY-I',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'DATABASE MANAGEMENT SYSTEM',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'DISCRETE MATHEMATICS',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'4th',
                'sub_name'=>'MARKETING MANAGEMENT',
            ],


            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Probability & Statistics',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Society & Ethics in IT',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Data Communication',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Web Technology - II',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Computer Graphics',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'5th',
                'sub_name'=>'Operating System',
            ],


            ['sf_id'=>$sf_id[0],
                'semester'=>'6th',
                'sub_name'=>'Embedded System Programming',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'6th',
                'sub_name'=>'Computer Network',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'6th',
                'sub_name'=>'Data Mining',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'6th',
                'sub_name'=>'Advance OOP JAVA',
            ],
            ['sf_id'=>$sf_id[0],
                'semester'=>'6th',
                'sub_name'=>'Research Methodology',
            ],


            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Mathematics- I',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Fundamentals of Information Technology',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Technical Communication (English)',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Basic Electrical System & Circuit',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Principles of Management',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'1st',
                'sub_name'=>'Computer Programming-I',
            ],


            ['sf_id'=>$sf_id2[0],
                'semester'=>'2nd',
                'sub_name'=>'Mathematics - II',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'2nd',
                'sub_name'=>'Electronics Devices & Circuits',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'2nd',
                'sub_name'=>'Digital Logic',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'2nd',
                'sub_name'=>'Object Oriented Programming in C++',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'2nd',
                'sub_name'=>'Financial management & Accounting',
            ],

            ['sf_id'=>$sf_id2[0],
                'semester'=>'3rd',
                'sub_name'=>'System Analysis & Design',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'3rd',
                'sub_name'=>'Microprocessor & Assembly Langu',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'3rd',
                'sub_name'=>'Data Structure & Algorithm',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'3rd',
                'sub_name'=>'User Interface Design',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'3rd',
                'sub_name'=>'Numerical Methods',
            ],

            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Communication System',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Computer Organization',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Web Technology-I',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Database Management System',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Discrete Mathematics',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'4th',
                'sub_name'=>'Marketing Management',
            ],

            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Probability & Statistics',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Society & Ethics in IT',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Data Communication',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Web Technology - II',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Computer Graphics',
            ],
            ['sf_id'=>$sf_id2[0],
                'semester'=>'5th',
                'sub_name'=>'Operating System',
            ],




            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Mathematics- I',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Fundamentals of Information Technology',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Technical Communication (English)',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Basic Electrical System & Circuit',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Principles of Management',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'1st',
                'sub_name'=>'Computer Programming-I',
            ],


            ['sf_id'=>$sf_id3[0],
                'semester'=>'2nd',
                'sub_name'=>'Mathematics - II',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'2nd',
                'sub_name'=>'Electronics Devices & Circuits',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'2nd',
                'sub_name'=>'Digital Logic',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'2nd',
                'sub_name'=>'Object Oriented Programming in C++',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'2nd',
                'sub_name'=>'Financial management & Accounting',
            ],

            ['sf_id'=>$sf_id3[0],
                'semester'=>'3rd',
                'sub_name'=>'System Analysis & Design',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'3rd',
                'sub_name'=>'Microprocessor & Assembly Langu',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'3rd',
                'sub_name'=>'Data Structure & Algorithm',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'3rd',
                'sub_name'=>'User Interface Design',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'3rd',
                'sub_name'=>'Numerical Methods',
            ],

            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Communication System',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Computer Organization',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Web Technology-I',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Database Management System',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Discrete Mathematics',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'4th',
                'sub_name'=>'Marketing Management',
            ],

            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Probability & Statistics',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Society & Ethics in IT',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Data Communication',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Web Technology - II',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Computer Graphics',
            ],
            ['sf_id'=>$sf_id3[0],
                'semester'=>'5th',
                'sub_name'=>'Operating System',
            ],







        ];
        DB::table('subjects')->insert($sub);
    }
}
